### ISSUE TITLE
Description Line Length

### ISSUE THREAD

**Issue by ByteAlex** [ZeroTwo-Bot/ZeroTwo-Bot#103]
**Describe the bug**
The description line length is defined in pixels, but currently it is shown by the amount of characters.

**To Reproduce**
- Make a description line on custom profile tab
- render it with the bot

**Expected behavior**
The same line length will rendered as shown in the designer preview

**Actual behaviour**
The renderer shown e.g. on 300 desc line length 1/4 of the image, but in the designer its about the half of the image.
Render is correct, because 300px / 1200px = 1 / 4

**Comment by pinnouse** [comment]
Should be fixed now, reopen if still not scaled correctly pls.
