### ISSUE TITLE
Welcome Greeting Images not loading

### ISSUE THREAD

**Issue by Xavinlol** [ZeroTwo-Bot/ZeroTwo-Bot#109]
**Describe the bug**
When opening the welcome greetings tab on the dashboard, there's nothing shown.

**To Reproduce**
1. Open Welcome Greeting Images Tab on the dashboard

**Expected behavior**
Dashboard should show Greeting Designer

**Comment by pinnouse** [comment]
Doesn't show if not in a premium enabled server, which server did you try?

**Comment by ByteAlex** [comment]
Please make it visible to non-premium servers aswell. The server should throw a 401 which you can use for showing a premium error message. - So they can see what they‘re missing :P

**Comment by pinnouse** [comment]
Opened welcome/farewell designer for all
