### ISSUE TITLE
Premium-Badge / Badge-Data

### ISSUE THREAD

**Issue by ByteAlex** [ZeroTwo-Bot/ZeroTwo-Bot#111]
We need to add another field to the existing ProfileRenderData, this is needed to render the premium badges.
When doing so I already had in mind keeping this as flexible as possible, so the new field is added on root level and is named `badge`.
Badge contains a object with the following data:
```
size: Int, // size of the badge in px
positionX: Int, // start position x
positionY: Int, // start position y
spaceSize: Int, // space between badges in px
maxCount: Int, // max amount of badges rendered
appendDirection: String // direction in which spaces additional badges will be appended
```

Can you please add that to the custom profile designer? @pinnouse 

@ruffrick Can you please add the badges to existing profiles when pinnouse implemented the designer?

**Comment by pinnouse** [comment]
what are the appendDirection strings?

**Comment by ByteAlex** [comment]
UP DOWN LEFT RIGHT, but you can leave maxCount and appendDirection out for now, I might rework them. I'm not yet sure about them, tbh.

**Comment by ruffrick** [comment]
Will do, @pinnouse just shoot me a dm when you're done

@ByteAlex Did you change anything except local urls in the JSON render data? Designer obviously doesn't like those, but if you haven't changed anything other than that I can use the local copies I have with the cdn urls.

**Comment by ByteAlex** [comment]
After some short discussion in discord, we agreed on changing the `badge` object to a `badges` array, which holds a object of
```
size: Int,
positionX: Int,
positionY: Int
```

**Comment by ByteAlex** [comment]
@ruffrick I don't know if I changed anything, I'll just give you access to the files I have

**Comment by ruffrick** [comment]
@pinnouse One bug i noticed, badges are rendered on a layer behind avatars

![Unbenannt](https://user-images.githubusercontent.com/64497918/82394569-b351e400-9a49-11ea-8032-0a045d104300.png)

**Comment by pinnouse** [comment]
Thanks ruff, fixed the display order issue
LOL I thought I was smart for having implemented that correctly then I realized I didn't lmao.
Closing seems like there aren't any more issues to report here.. Hopefully.

**Comment by ByteAlex** [comment]
Implemented & done
