### ISSUE TITLE
Profiles chopped off on mobile

### ISSUE THREAD

**Issue by ruffrick** [ZeroTwo-Bot/ZeroTwo-Bot#119]
Profiles aren't correctly scaled in the embed on mobile, so the sides are chopped off unless you actually click the image and open the preview.
Might wanna think about making it a normal message instead of an embed?
![Screenshot_20200528-150700](https://user-images.githubusercontent.com/64497918/83145385-ffa9bd80-a0f4-11ea-97f1-a035fa1c1739.png)

**Comment by ByteAlex** [comment]
![grafik](https://user-images.githubusercontent.com/2230292/83152929-a777b900-a0fe-11ea-96cb-52ce28a081f0.png)
iPhone X

**Comment by ByteAlex** [comment]
Discord Bug - To be fixed by them
