### ISSUE TITLE
Fix description line start

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#69]
![image](https://user-images.githubusercontent.com/51034573/81352398-be5e5900-90c6-11ea-9891-a9031ff7b0de.png)
![image](https://user-images.githubusercontent.com/51034573/81352400-bf8f8600-90c6-11ea-90ba-b3c6cc5ced2f.png)

**Comment by ByteAlex** [comment]
@ruffrick This is also related to you if I see correctly, cause both images are from v2, but they have different starting points. I treated this image as "description linke breaks broken" ticket, but it seems to be exactly whats writting in the title

**Comment by ByteAlex** [comment]
The splitting part of this is done, awaiting @ruffrick to fix the desc lines start offset

**Comment by ByteAlex** [comment]
Fixed
