### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#70]
should zerotwo have nsfw options turned off from the start with annotation that it is possible to turn it on in web settings?

**Comment by ByteAlex** [comment]
I don't think this is a good idea, a lot of users want to use the NSFW features and most users don't find the dashboard smh.
So it'll be better to have it enabled by default. Big servers know how bots work and will find the dashboard real quick, so these servers will find the option to disable that.
