### ISSUE TITLE
Fix divorce

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#74]
![image](https://user-images.githubusercontent.com/51034573/81473554-8e66a100-91ff-11ea-813e-4644bfbba4a8.png)
![image](https://user-images.githubusercontent.com/51034573/81473556-8f97ce00-91ff-11ea-81bf-bc649cf720f4.png)
![image](https://user-images.githubusercontent.com/51034573/81473557-90c8fb00-91ff-11ea-85e1-6092fb72ec88.png)

**Comment by ByteAlex** [comment]
So if I see correctly the other user's marriage wasn't unbound properly?

**Comment by BONBONauzWURST** [comment]
yes

**Comment by ByteAlex** [comment]
Can't reproduce
