### ISSUE TITLE
Polish language = wrong date in profile

### ISSUE THREAD

**Issue by Test20C** [ZeroTwo-Bot/ZeroTwo-Bot#75]
![1](https://user-images.githubusercontent.com/65074375/81474142-bc4de480-9203-11ea-91b5-b0007824b4be.jpg)
![2_LI](https://user-images.githubusercontent.com/65074375/81474143-bce67b00-9203-11ea-8854-9f9fe560747f.jpg)

**Comment by BONBONauzWURST** [comment]
Fixed only need to update translation

**Comment by ByteAlex** [comment]
Fixed by translation update
