### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by DennisSaurus** [ZeroTwo-Bot/ZeroTwo-Bot#77]
Can't play musik on Zero Two canary

**Comment by ByteAlex** [comment]
Can you please try and see if the bug still occurres for you?

**Comment by BONBONauzWURST** [comment]
![image](https://user-images.githubusercontent.com/51034573/81513422-af76e100-9328-11ea-8229-d2d02e8ffed7.png)
it says playing but nothing happens

**Comment by ByteAlex** [comment]
Can't reproduce
