### ISSUE TITLE
fix save/update button reaction roles

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#82]
https://cdn.discordapp.com/attachments/709174108293824533/709176066576613406/unknown.png

my age = 21
bot is set to give if = 21
but don't update it and also don't show changes on web
if set age to more than 20 won't do anything too

**Comment by ByteAlex** [comment]
Can you explain this again a little more detailed? @BONBONauzWURST

**Comment by BONBONauzWURST** [comment]
tried to reproduce to give better feedback but looks like its fixed when solving another bug so its 
SOLVED
