### ISSUE TITLE
change ms

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#86]
![image](https://user-images.githubusercontent.com/51034573/81513098-2199f680-9326-11ea-9e15-d0a2f0d3be98.png)
change it to let user choose date or to set it as days hours minutes seconds cause it make no sense to write in ms

**Comment by pinnouse** [comment]
😢ok

**Comment by pinnouse** [comment]
![image](https://user-images.githubusercontent.com/11915698/81970314-512e5480-95ed-11ea-81d9-04b888299d21.png)
kept it simple with a button to convert your times into ms
