### ISSUE TITLE
fix remove message

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#87]
![image](https://user-images.githubusercontent.com/51034573/81513168-966d3080-9326-11ea-9a06-ea80606bfe09.png)
when removed message on discord then cannot remove it on web

**Comment by ByteAlex** [comment]
This should actually not be a bug, this means you were trying to delete a message which was already deleted.
Did you delete the discord message before you did that?
Did the message disappear from the dashboard after that?

**Comment by BONBONauzWURST** [comment]
yes i deleted discord message before.
no it won't disappear at all.
imo you should be able to deletem message in dashboard even if zt cannot find message in discord

**Comment by ByteAlex** [comment]
Thanks for the clarification, I'll have a look on that

**Comment by ByteAlex** [comment]
Solved
