### ISSUE TITLE
missing

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#88]
![image](https://user-images.githubusercontent.com/51034573/81513191-d3d1be00-9326-11ea-9afc-eba38eae6a27.png)
add no requirements

**Comment by BONBONauzWURST** [comment]
also there is no gender requirement

**Comment by ByteAlex** [comment]
No requirement is used when you never add one, am I right @pinnouse ?
Even though this might be confusing for users, maybe we want to add that, OP?

**Comment by pinnouse** [comment]
Defaults to an empty rules indicator now
