### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#89]
![image](https://user-images.githubusercontent.com/51034573/81513245-3aef7280-9327-11ea-976c-cad529ce4d49.png)

**Comment by BONBONauzWURST** [comment]
might be caused coz previous deleting of message throw error too

**Comment by ByteAlex** [comment]
Due to a redis-error this morning old logs were gone due to a restart hell in all services.
Can you please try to reproduce that? @BONBONauzWURST

**Comment by ByteAlex** [comment]
Duplicates #87
