### ISSUE TITLE
Cannot have more than 1 reaction role

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#90]
![2](https://user-images.githubusercontent.com/51034573/81513320-fd3f1980-9327-11ea-8abe-64e453920d88.gif)
where's previous one?

**Comment by ByteAlex** [comment]
@pinnouse This looks like you're only showing the latest one, can you check that please?

**Comment by pinnouse** [comment]
@ByteAlex end point is only returning the latest
![image](https://user-images.githubusercontent.com/11915698/81968267-2a225380-95ea-11ea-9d18-270f5fdd9cef.png)

**Comment by ByteAlex** [comment]
Fixed
