### ISSUE TITLE
Implement left-over cardgame commands

### ISSUE THREAD

**Issue by ByteAlex** [ZeroTwo-Bot/ZeroTwo-Bot#92]
- Card Fight (util class WIP, gonna add to this ticket when done)
- Transfer (You remove card from users's card list via delta-builder `replace` method)
- Sell (via `CardgameCard#value()`)
- powerup (lurk from old implementation)

**Comment by ByteAlex** [comment]
@ToxicMushroom to calculate a fights outcome, use `CardgameFight(cardA: CardgameCard, cardB: CardgameCard, usernameA: String, usernameB: String)`
(Rebase on current master)

**Comment by ByteAlex** [comment]
This is a class constructor though (stupidly converted from current version), contains basically 2 exposed fields:
winner & combatLog

**Comment by ByteAlex** [comment]
Before you start this, remember to rebase. I changed a few methods

**Comment by ToxicMushroom** [comment]
I did :)

**Comment by ByteAlex** [comment]
Card Sell:
- `-1` for the index pls :P <3
- Sell confirmation

Card Fight:
- Nothing happens after you chose the bet

**Comment by ByteAlex** [comment]
Also please rebase, as I had to do one more fix for the constructors
