### ISSUE TITLE
Adding reaction

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#95]
**Describe the bug**

**To Reproduce**
1)follow gif
![heck2](https://user-images.githubusercontent.com/51034573/81694030-1bf4fb80-9461-11ea-8fd7-2b9249791186.gif)

**Expected behavior**

**Device Information**
 - OS: Windows 10
 - Browser edge on chromium
 - Setting reaction roles

**Additional context**
bot has all needed permissions
also 1st emoji is unchangeable 

time stamp: 1589287862265

![image](https://user-images.githubusercontent.com/51034573/81694423-9887da00-9461-11ea-8ed2-514c29ab04fb.png)

**Comment by ByteAlex** [comment]
Can't reproduce

**Comment by ByteAlex** [comment]
![grafik](https://user-images.githubusercontent.com/2230292/81749956-e970f000-94ac-11ea-8e4d-75d321a8241e.png)
With auto-role 2 having a requirement for age > 25

**Comment by BONBONauzWURST** [comment]
OK seems it affect only my server since i broke messages by deleting on discord
tested on other one and it worked

**Comment by ByteAlex** [comment]
Solved
