### ISSUE TITLE
NSFW commands error 400 

### ISSUE THREAD

**Issue by BONBONauzWURST** [ZeroTwo-Bot/ZeroTwo-Bot#96]
![image](https://user-images.githubusercontent.com/51034573/81711194-ab0b0f00-9473-11ea-9b69-7b039454584e.png)
![image](https://user-images.githubusercontent.com/51034573/81711225-b4947700-9473-11ea-9a1a-e47d9b3b92c0.png)

**Comment by ByteAlex** [comment]
Fixed
